polls/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from .views import Login, Logout, NewUser, PollList, PollDetail, NewPoll, DeletePoll

app_name = 'polls'

urlpatterns = [
    path('', PollList.as_view(), name='index'),
    path('vote/<int:pk>/', PollDetail.as_view(), name='vote'),
    path('new/', NewPoll.as_view(), name='new_poll'),
    path('delete/<int:pk>/', DeletePoll.as_view(), name='delete_poll'),
    path('register/', NewUser.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]


urlpatterns += staticfiles_urlpatterns()

portal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='polls/')),
    path('poll/', RedirectView.as_view(url='/polls/')),
]

polls/models.py
from django.db import models

class Poll(models.Model):
    question = models.CharField(max_length=2500)
    pub_date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='polls')

    def __str__(self):
        return self.question

class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text
    
class Vote(models.Model):
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, related_name='votes')
    voter = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['voter', 'choice'], name='unique_vote_per_poll')
        ]

polls/forms.py
from django import forms
from .models import Poll, Choice
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['question']
        widgets = {
            'question': forms.TextInput(attrs={'class': 'form-control'})
        }

ChoiceFormSet = inlineformset_factory(Poll, Choice, fields=['choice_text'], extra=2, can_delete=False,
    widgets={'choice_text': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter choice'})},
    labels={'choice_text': 'Choice'})

class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden
from .models import Poll, Choice, Vote
from .forms import PollForm, ChoiceFormSet, UserCreateForm
from django.urls import reverse
from django.views.generic import DeleteView, ListView, DetailView, CreateView, FormView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required


class Login(FormView):
    form_class = AuthenticationForm
    template_name = 'polls/login.html'

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('polls:index')


class Logout(LoginRequiredMixin, FormView):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('polls:index')


class NewUser(FormView):
    form_class = UserCreateForm
    template_name = 'polls/register.html'
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))
    
    def get_success_url(self):
        return reverse('polls:login')
    

class PollList(ListView):
    model = Poll
    template_name = 'polls/index.html'
    context_object_name = 'polls'
    
    
class PollDetail(DetailView):
    model = Poll
    template_name = 'polls/poll.html'
    context_object_name = 'poll'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['choices'] = self.object.choices.all()
        return context
    
    def post (self, request, *args, **kwargs):
        poll = self.get_object()
        choice_id = request.POST.get('choice')
        choice = poll.choices.get(pk=choice_id)
        if Vote.objects.filter(voter=request.user, choice__poll=poll).exists():
            return HttpResponseForbidden("You have already voted on this poll.")
        Vote.objects.create(choice=choice, voter=request.user)
        return redirect('polls:vote', pk=poll.pk)
    
    
class NewPoll(LoginRequiredMixin, CreateView):
    model = Poll
    form_class = PollForm
    template_name = 'polls/new_poll.html'
    login_url = 'polls:login'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = ChoiceFormSet(self.request.POST)
        else:
            context['formset'] = ChoiceFormSet()
        return context
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect('polls:index')
        else:
            return self.render_to_response(self.get_context_data(form=form))
    
    def get_success_url(self):
        return reverse('polls:index')


class DeletePoll(DeleteView):
    model = Poll

    def get_success_url(self):
        return reverse('polls:index')

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    {% block title %}
    <title>
        Polling App
    </title>
    {% endblock %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'polls:index' %}"><i class="fa-solid fa-poll"></i> Alantin Polls</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                    {{ user.username }} <a href="{% url 'polls:logout' %}" button class="btn btn-warning"><i class="fa-solid fa-user"></i>Sign out</button></a></h1>
                {% else %}
                    <a href="{% url 'polls:login' %}" button class="btn btn-primary"><i class="fa-solid fa-user"></i>Sign In</button></a>
                {% endif %}
            </li>
    </div>
    

</nav>    
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    {% block head%}{% endblock %}
</head>
<body>
    {% block body%}{% endblock %}
</body>
</html>

polls/templates/polls/index.html
{% extends "base.html" %}
{% block body%}
<body>
    <div class= "container">
        <h1>All Polls</h1>
        <div class="row row-cols-1">
            {% if polls %}
                {% for poll in polls %}
                <div class="row">
                    <div class="col">
                        <div class="card mb-4 poll-card">
                            <a href="{% url 'polls:vote' poll.pk %}" class="text-decoration-none text-dark">
                                <h3 class="card-header">{{ poll.question }}</h3>
                                <div class="card-body">
                                    <ul class="list-group list-group-flush">
                                        {% for choice in poll.choices.all %}
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                <span>{{ choice.choice_text }}</span>
                                                <span>{{ choice.votes.count }} votes</span></li>
                                        {% endfor %}
                                    </ul>
                                    <a href="{% url 'polls:vote' poll.pk %}" class="btn btn-sm btn-primary"><i class ="fa fa-check-square"></i> Vote</a>
                                </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>There are no polls at this time.</p>
            {% endif %}
        </div>
        <div class="row">
            <div class="col-md-6">
                <p><a class="btn btn-primary btn-lg" href="{% url 'polls:new_poll' %}" role="button"><i class="fa fa-pencil"></i> New Poll </a></p>
            </div>
        </div>
    </div>
</body>
{% endblock %}  
</html>

polls/templates/polls/login.html
{% extends "base.html" %}
{% block body%}
    <div class= "container">
        <h1>Sign In</h1>
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Sign In</button>
                </form>
            </div>
        </div>
        <h2>Don't have an account? <a href="{% url 'polls:register' %}" button class="btn btn-primary"><i class="fa-solid fa-user"></i>Create One</button></a></h2>
    </div>
{% endblock %}

polls/templates/polls/logout.html
{% extends "base.html" %}
{% block body%}
    <div class= "container">
        <h1>Are you sure you want to sign out?</h1>
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Sign Out</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

polls/templates/polls/new_poll.html
{% extends "base.html" %}
{% block head %}
<script>
    function addChoiceField() {
        console.log("Button clicked");
        let formIdx = document.getElementById("id_choices-TOTAL_FORMS").value;
        let newField = document.getElementById("empty-form").innerHTML.replace(/__prefix__/g, formIdx);
        document.getElementById("choices-container").insertAdjacentHTML("beforeend", newField);
        document.getElementById("id_choices-TOTAL_FORMS").value = parseInt(formIdx) + 1;
    }
</script>
{% endblock %}
{% block body%}
<body>
    <div class="container">
        <h1>New Poll</h1>
        <form method="post">
            {% csrf_token %}
            <div>
                <h3>Ask a question</h3>
                {{ form.as_p }}
            </div>
            
            <h3>What are the answers you want people to choose between?</h3>
            <button type="button" class="btn btn-success btn-xs" onclick="addChoiceField()">+</button> Add Choice
            <div id="choices-container">
                {{ formset.management_form }}
                {% for form in formset %}
                    <div class="choice-form">{{ form.as_p }}</div>
                {% endfor %}
            </div>
            <br></br>
            <button type="submit" class="btn btn-primary">Create Poll</button>

            <!-- Empty form template for cloning -->
            <div id="empty-form" style="display: none;">
                {{ formset.empty_form.as_p }}
            </div>
        </form>
    </div>
</body>
{% endblock %}
</html>

polls/templates/polls/poll.html
{% extends "base.html" %}
{% block body%}
<body>
    <div class= "container">
        <form method="post">
            {% csrf_token %}
            <div class="card mb-4 poll-card">
            <h3 class="card-header d-flex justify-content-between align-items-center">
                <span><a HREF="{% url 'polls:index' %}" class="btn btn-primary btn-custom btn-space"><i class="fa-solid fa-less-than"></i></a>{{ poll.question }}</span>
                <span> Owner: {{poll.owner.username}}</span>
            </h3>
                <div class="card-body">
                    <ul>
                        {% for choice in poll.choices.all %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>{{ choice.choice_text }}</span>
                            <span>{{ choice.votes.count }} votes</span></li>
                        {% endfor %}
                    </ul>
                    {% if user.is_authenticated %}
                    <label for="choice">Choose an option:</label>
                    <select name="choice" id="choice">
                        {% for choice in poll.choices.all %}
                            <option value="{{ choice.id }}">{{ choice.choice_text }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit">Vote</button>
                    {% else %}
                    <p>You must be logged in to vote.</p>
                    {% endif %}
                </div>
            </div>
            {% if user.username == poll.owner.username or user.is_superuser %}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <A class="btn btn-danger btn-xs" HREF="{% url 'polls:delete_poll' poll.pk %}">Delete</A>
                    </div>
                    {% endif %}
        </form>
    </div>
</body>
{% endblock %}

polls/templates/polls/poll_confirm_delete.html
{% extends "base.html" %}
{% block body %}
<div class= "container alert-danger">
    <h1>Confirmation</h1>
<div class="alert alert-danger" role="alert">Are you sure you wish to delete this poll?</div>
<form action="." method="POST">
    {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes</button>
</form>
{% endblock %}
</html>

polls/templates/polls/register.html
{% extends "base.html" %}
{% block body%}
    <div class= "container">
        <h1>Create a User Account</h1>
        <form method="post">
            {% csrf_token %}
            <h5>{{form.username.label}}</h5>
            {{form.username}}
            <h5>{{form.password1.label}}</h5>
            {{form.password1}}
            <h5>{{form.password2.label}}</h5>
            {{form.password2}}
            <ul>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can’t be entirely numeric</li>
            </ul>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
        {% if form.errors %}
        <div class="errors">
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
{% endblock %}

polls/templates/polls/vote.html
{% extends "base.html" %}
{% block body%}
<body>
    <div class= "container">
        <h1>Vote on Poll</h1>
        <form method="post">
            {% csrf_token %}
            <div class="card mb-4 poll-card">
            <h3 class="card-header"><button class="btn btn-primary btn-custom btn-space"><i class="fa-solid fa-less-than"></i></button></i>{{ poll.question }}</h3>
                <div class="card-body">
                    <ul>
                        {% for choice in poll.choice_set.all %}
                            <li>{{ choice.choice_text }} - {{ choice.votes }} votes</li>
                        {% endfor %}
                    </ul>
                    <label for="choice">Choose an option:</label>
                    <select name="choice" id="choice">
                        {% for choice in poll.choice_set.all %}
                            <option value="{{ choice.id }}">{{ choice.choice_text }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit">Vote</button>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <A class="btn btn-danger btn-xs" HREF="{% url 'polls:delete_poll' poll.pk %}">Delete</A>
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>
{% endblock %}